#
# Dockerfile for machine learning stack
#
#
# FROM docker.io/centos/python-36-centos7
FROM nvidia/cuda:9.0-cudnn7-runtime-centos7
MAINTAINER Bob Kozdemba <bkozdemba@gmail.com>
EXPOSE 8888 6006
    
### Setup user for build execution and application runtime
ENV APP_ROOT=/opt/app-root
RUN mkdir -p ${APP_ROOT}/{bin,src} && \
    chmod -R u+x ${APP_ROOT}/bin && chgrp -R 0 ${APP_ROOT} && chmod -R g=u ${APP_ROOT}
ENV PATH=${APP_ROOT}/bin:${PATH} HOME=${APP_ROOT}

USER root

RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum -y install python2-pip python-devel libgomp gcc
RUN easy_install -U pip
RUN pip install --upgrade tensorflow-gpu matplotlib pillow scipy jupyter theano keras sklearn scikit-image
# RUN pip install --upgrade tensorflow-gpu 

### Containers should NOT run as root as a good practice
USER 1001
# USER root
WORKDIR ${APP_ROOT}

### user name recognition at runtime w/ an arbitrary uid - for OpenShift deployments
# ENTRYPOINT [ "uid_entrypoint" ]
VOLUME ${APP_ROOT}/logs ${APP_ROOT}/data

CMD /usr/bin/tail -f /dev/null

